version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: docker-postgres
    environment:
      POSTGRES_PASSWORD: 'supersecret123'
    ports:
      - 5432:5432

  server:
    build: .
    command: npm run start
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - postgres
    links:
      - postgres

  migrate:
    build: .
    command: npx prisma migrate reset --force
    environment:
      - DATABASE_URL=postgresql://postgres:supersecret123@docker-postgres:5432/mydb?schema=public
      - YEAR_RANGE=10
      - CURRENT_YEAR=2020
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  seed:
    build: .
    command: npm run seed:fill
    environment:
      - DATABASE_URL=postgresql://postgres:supersecret123@docker-postgres:5432/mydb?schema=public
      - YEAR_RANGE=10
      - CURRENT_YEAR=2020
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - migrate

  tests:
    build: .
    command: >
      sh -c 'sleep 10 && npm run test:e2e'
    environment:
      - DATABASE_URL=postgresql://postgres:supersecret123@docker-postgres:5432/mydb?schema=public
      - YEAR_RANGE=10
      - CURRENT_YEAR=2020
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - migrate
      - seed

  lint:
    build: .
    command: npx eslint src/
    volumes:
      - .:/app
      - /app/node_modules
